### ISSUE TITLE
Firehose implementation checklist

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/firehose-arweave#9]
## CHECKLIST

- [ ] Having a document that explains the Arweave blockchain execution model and blocks flowing, which should include the following sections:
  - [x] Block linking, how blocks are linked together, which field(s) of the model links block to its parent, are blocks link somehow to forked/uncles block.
  - [ ] Block finality and how it is handled within the chain (is it a probabilistic model like Ethereum or does it have a finality concept, which fields of the block determines its finality if it’s a final model, what is the longuest expected fork is it’s a probabilistics model)
  - [ ] Block’s important fields documentation, what are the semantic meaning of the fields, relation to the execution models, to the block linking models, to forking, etc.
  - [ ] Execution model of transactions, what a transaction contains, want “execution” can happen, what’s the full model of a transaction
  - [ ] Description of the algorithm of how live blocks will be tracked by the polling code
  - [ ] Description of the algorithm of how forks will be handled by the polling code and how we will handle those cases
  - [ ] Run a series of acceptance tests at the gRPC level for ensuring Firehose on Arweave works as expected (see section below)
  - [ ] Define the process that will be required to fill the entire history of blocks, ensures it works properly
